---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: true

# Install ansible
addons:
  apt:
    packages:
    - python-pip

matrix:
  include:
    - env: TEST_SUITE="-e papertrail_enable_tcp=True"  #TCP
    - env: TEST_SUITE="-e papertrail_enable_tls=True"  #TCP TLS
install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory -e @tests/required-vars.yml $TEST_SUITE

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
